version: "3"

services:

  backend:
    build: .
    container_name: server
    restart: always
    ports:
      - 5000:5000
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - DB_URI=mongodb://mongo:27017
    depends_on:
      - mongo
    networks:
      - express-mongo

  mongo:
    container_name: mongo
    restart: always
    image: mongo:6.0.14
    volumes:
      - ./data:/data/db
    networks:
      - express-mongo
    expose:
      - 27017
networks:
  express-mongo: